# Generated by Django 5.2.1 on 2025-05-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='dt_creation',
            new_name='dt_created',
        ),
    ]
