# Generated by Django 5.2.1 on 2025-05-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_transacao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
